[workspace]
resolver = "2"
members = ["displaylight", "lights", "firmware"]

[workspace.dependencies]
screen_capture = { git = "https://github.com/iwanders/screen_capture", rev = "5ea925c4fb87665836be2a683cafd25945f75bd8" }

[profile.release]
opt-level = 3

[profile.firmware]
#opt-level = "z"
#opt-level = 3
inherits = "release"
incremental = false
codegen-units = 1
debug = true
lto = true
