[workspace]

members = [
    "screen_capture",
    "displaylight",
    "lights",
    "firmware",
]


[profile.release]
opt-level = 3

[profile.firmware]
#opt-level = "z"
#opt-level = 3
inherits = "release"
incremental = false
codegen-units = 1
debug = true
lto = true
