
# The rate at which the update loop will run.
rate: 60.0

# The serial port to connect to.
port: COM7

# Vertical depth of zones used for sampling.
vertical_depth: 200

# Horizontal depth of zones used for sampling.
horizontal_depth: 200

# Distance between pixels to be sampled.
sample_pixel_distance: 15

# Whether or not to diagonalize the points to be sampled. This attempts to avoid the sample
# points making horizontal and vertical lines.
sample_diagonalize_points: true

# Number of bisections to perform per side.
edge_detection_bisect_count: 8

# Only allow edge change if the bisection result was a rectangle with straight borders.
edge_detection_rectangular_only: true

# If edge detection is disabled, the full width and height of the image is always used.
edge_detection_enable: true

# Limiting factor between 0.0 and 1.0, 1.0 allows full brightness. 0.5 specifies half brightness.
limiting_factor: 0.5

capture:
  -
    display: 0