[package]
name = "displaylight"
version = "0.0.0"
edition = "2021"

[dependencies]
desktop_frame = { path = "../screen_capture" }
lights = { path = "../lights" }
clap = "2.34.0"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
